### ISSUE TITLE
对于expire的key，可以显示还剩多少时间

### ISSUE THREAD

**Issue by turbidsoul** [cinience/RedisStudio#15]
对时间格式化，可以显示还剩多少小时分秒，或者显示成到到2014-01-01 01:01:01
根据不同的设置来确定具体如何显示

**Comment by cinience** [comment]
已增加该功能，功能太小，合并到v0.1.3，刚更新上去，请下载最新的试用。
https://github.com/cinience/RedisStudio/releases/tag/0.1.3
