### ISSUE TITLE
0.1.4/0.1.5 版本总是提示 Please select a item

### ISSUE THREAD

**Issue by yorkxiao** [cinience/RedisStudio#18]
双击 DB-0 不能列出keys。

**Comment by wzgogogo** [comment]
0.1.5列不出keys

**Comment by chuizi2008** [comment]
我也出现这个问题。。跟踪代码发现在RedisClient.cpp第96行
ScopedRedisReply reply(Command("scan %d COUNT 1000", iternum));
执行scan的时候，报scan命令无法识别...

我的redis版本为老版本，2.4不支持scan,2.8版本才开始支持scan命令的...

要解决这个问题，升级一下redis吧

**Comment by cinience** [comment]
建议如果条件允许，请升级到redis 2.8以上吧，另外可以帮忙fix这个bug哦
