### ISSUE TITLE
建议不要一次性加载所有database，我的redis 99999个数据库，加载到卡死

### ISSUE THREAD

**Issue by lingting** [cinience/RedisStudio#50]
可以添加一个配置， 加载多少到多少的数据库。。 不然数据库一多久烦死

**Comment by zmlu** [comment]
这么多数据库为啥还用这么古老的客户端呢？

**Comment by lingting** [comment]
> 这么多数据库为啥还用这么古老的客户端呢？

说的很有道理，这个 issues 提交完后没几天我就换工具了, 最后到现在回归到命令行.
